version: "3.3"
services:
  db:
    ports:
      - "5432:5432"
  pgadmin:
    ports:
      - "5050:5050"
    volumes:
      - ./deployment/pg_admin/servers.json:/pg_admin/servers.json
  backend:
    ports:
      - "9080:80"
    volumes:
      - ./app:/app
    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    # command: bash -c "while true; do sleep 1; done"  # Infinite loop to keep container live doing nothing
    command: /app/scripts/test.sh
